name: Deploy to Docker Hub and Run Container

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: adnanifrah
          password: Adnan2001@
          
      - name: Build and push Docker image
        run: |
          docker build -t adnanifrah/tp2:latest .
          docker push adnanifrah/tp2:latest

      - name: Connect to Docker Desktop
        run: |
          export DOCKER_HOST=tcp://localhost:2375

      - name: Remove old container
        run: |
          docker stop tp2-container || true
          docker rm tp2-container || true

      - name: Run new container
        run: |
          docker run -d -p 80:80 --name tp2-container adnanifrah/tp2:latest
