name: Deploy to Docker Desktop

on:
  push:
    branches:
      - master # Exécute le workflow à chaque commit sur main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Vérifiez si l'installation est réussie

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: adnanifrah
          password: Adnan2001@

      - name: Build and push Docker image
        run: |
          docker-compose build
          docker-compose push

      - name: Connect to Docker Desktop
        run: |
          export DOCKER_HOST=tcp://localhost:2375

      - name: Stop and remove old container
        run: |
          docker-compose down  # Arrête et supprime les conteneurs existants

      - name: Run new container
        run: |
          docker-compose up -d  # Démarre le conteneur en mode détaché
